version: '3.8'

services:
  yue-exllamav2-interface:
    image: alissonpereiraanjos/yue-exllamav2-interface:latest
    container_name: yue-exllamav2-interface
    restart: unless-stopped
    ports:
      - "7860:7860"
      - "8888:8888"
    environment:
      - DOWNLOAD_MODELS=xcodec_mini_infer,YuE-s1-7B-anneal-en-cot,YuE-s1-7B-anneal-en-icl
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /home/amir/Desktop/yue_files/models:/workspace/models
      - /home/amir/Desktop/yue_files/outputs:/workspace/outputs
      - /home/amir/Desktop/BirthdaySongs:/code_base

